FROM python:3.11

WORKDIR /code

RUN apt-get update && apt-get install vim iputils-ping telnet curl awscli gettext-base yq jq -y

RUN apt-get update && apt-get install -y gnupg software-properties-common

RUN wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

RUN gpg --no-default-keyring \
    --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    --fingerprint

RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    tee /etc/apt/sources.list.d/hashicorp.list


RUN apt update

RUN apt-get install terraform

COPY templates /templates
COPY setupenv.sh /setupenv.sh

ENTRYPOINT [ "sh", "/setupenv.sh"]